name: CI - Dockerized Amazon Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t amazon-tests .

      - name: Run tests in Docker and extract Allure results
        run: |
          docker run --name amazon-tests-container amazon-tests
          docker cp amazon-tests-container:/app/allure-results ./allure-results || echo "No allure results found"
          docker rm amazon-tests-container

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.21.1/allure-2.21.1.zip
          unzip -o allure-2.21.1.
